### ISSUE TITLE
Python version error when installing requirements 

### ISSUE THREAD

**Issue by Kimthanh27** [ShmuelRonen/ComfyUI_wav2lip#2]
There is a problem with installing the requirements, and there is an error related to the Python version. May I ask if your node requires a specific Python version? The node does not show up in the ComfyUI interface.

**Comment by ShmuelRonen** [comment]
Here the versions list:

E:\ComfyUI_4ALL>python check.py
| Python | Python 3.10.6 |
| PyTorch | 2.3.0+cu118 |
| torchvision | 0.18.0 |
| numpy | 1.25.2 |
| scipy | 1.13.0 |
| opencv-python | 4.8.0.76 |
| Pillow | 10.3.0 |
| tqdm | 4.66.2 |
| tensorflow | 2.16.1 |
WARNING: Package(s) not found: tensorflow-gpu
| tensorflow-gpu | Not installed |
| PyYAML | 6.0.1 |
| scikit-image | 0.22.0 |
| tb-nightly | 2.17.0a20240405 |
| yapf | 0.40.2 |
| lmdb | 1.4.1 |
| addict | 2.4.0 |
| future | 1.0.0 |
| requests | 2.31.0 |
| gfpgan | 1.3.8 |
| realesrgan | 0.3.0 |
| pydub | 0.25.1 |
| soundfile | 0.12.1 |
| scikit-image | 0.22.0 |
| lpips | 0.1.4 |

**Comment by laidingq** [comment]
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI_wav2lip\__init__.py", line 1, in <module>
    from .wav2lip import Wav2Lip
  File "D:\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py", line 35, in <module>
    from wav2lip import Wav2Lip
  File "D:\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py", line 35, in <module>
    from wav2lip import Wav2Lip
**ImportError: cannot import name 'Wav2Lip' from partially initialized module 'wav2lip' (most likely due to a circular import) (D:\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py)**

Cannot import D:\ComfyUI\custom_nodes\ComfyUI_wav2lip module for custom nodes: cannot import name 'Wav2Lip' from partially initialized module 'wav2lip' (most likely due to a circular import) (D:\ComfyUI\custom_nodes\ComfyUI_wav2lip\wav2lip.py)

**Comment by ShmuelRonen** [comment]
Are you make git pull to the last version of today?

**Comment by laidingq** [comment]
> 你让 git pull 到今天的最后一个版本了吗？

yes
